### PR TITLE
Update 5min.sh

### PR DESCRIPTION
**Pull request by hulto**
security metrics +100

### CODE REVIEW

**Comment by DolphinPhishing** [comment]
I've reviewed and it looks great to me, look forward to seeing the PR get accepted

**Comment by hackersoup** [comment]
This meets all of my stringent security standards

**Comment by hulto** [comment]
image
What is monika's password?

**Comment by mav8557** [comment]
LGTM :+1:

**Review by drew-young — APPROVED** [review]
love it.

**Comment by mdbook** [comment]
Slight security issue detected with this pull request; unfortunately, I will have to deny the request.

**Pull request closed without merging**
